name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      packages: write  # Required for pushing to GHCR
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Log in to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: |
        docker build . -f docker/Dockerfile --tag ghcr.io/mfmceneaney/clas12-analysis:latest

    - name: Push image to GHCR
      run: |
        docker push ghcr.io/mfmceneaney/clas12-analysis:latest
