name: Generate Groovydoc

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # needed to push changes back to repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Groovydoc inside container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/mfmceneaney/clas12-analysis-docker:latest
          options: -v ${{ github.workspace }}:/usr/src -w /usr/src
          run: ./gradlew generateGroovydoc --no-daemon

      - name: Commit and push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/_static
          git diff --cached --quiet || git commit -m "Update Groovydoc after PR merge"
          git push
