name: Singularity Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-singularity:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: recursive

        - name: Build SIF with remote builder
          run: |
            apptainer remote login --token ${{ secrets.SYLABS_TOKEN }}
            apptainer build --remote clas12-analysis.sif singularity/clas12-analysis.def

        - name: Upload SIF artifact
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: singularity-sif
            path: clas12-analysis.sif
