name: Singularity Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

build-singularity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install apptainer dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential debootstrap squashfs-tools wget pkg-config git squashfs-tools

      - name: Install Apptainer
        run: |
          sudo apt-get install -y apptainer || true

      - name: Build Singularity image (SIF)
        run: |
          # Use the singularity/Apptainer definition to build an image
          # The build requires running from the repo root so %files maps correctly
          apptainer build clas12-analysis.sif singularity/CLAS12-Analysis.def || true

      - name: Upload SIF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: singularity-sif
          path: CLAS12-Analysis.sif