name: Singularity Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    container:
      image: quay.io/singularity/singularity:v4.3.1
      options: --privileged

    name: Build Container
    steps:

      - name: Check out code for the container builds
        uses: actions/checkout@v4

      - name: Build Singularity Image
        run: |
           singularity build clas12-analysis.sif singularity/clas12-analysis.def

      - name: Install curl (Alpine)
        run: apk add --no-cache curl

      - name: Install ORAS CLI
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v1.3.0/oras_1.3.0_linux_amd64.tar.gz
          tar -xvf oras_1.3.0_linux_amd64.tar.gz
          sudo mv oras /usr/local/bin/

      - name: Push SIF to GHCR using ORAS
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCR_USERNAME: ${{ github.repository_owner }}
          tag: latest
        run: |
          echo $GHCR_TOKEN | oras login ghcr.io -u $GHCR_USERNAME --password-stdin
          oras push ghcr.io/${{ github.repository }}-singularity:latest \
            --annotation "org.opencontainers.image.title=clas12-analysis.sif" \
            clas12-analysis.sif:application/vnd.sylabs.sif.layer.v1.sif
